// File generated by Antigravity AI assistant.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMra4qo0e-kvmqt5Mtn20vu72a22ZlrtU',
    appId: '1:522154987711:web:10cbcfd70dd4ecba3df60a',
    messagingSenderId: '522154987711',
    projectId: 'familymedicinetracker-app',
    authDomain: 'familymedicinetracker-app.firebaseapp.com',
    storageBucket: 'familymedicinetracker-app.firebasestorage.app',
    databaseURL: 'https://familymedicinetracker-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnl-QCWJJt3M23Qv7vBxudi17NBqUlZE',
    appId: '1:522154987711:android:2e5dd2763f5d06513df60a',
    messagingSenderId: '522154987711',
    projectId: 'familymedicinetracker-app',
    storageBucket: 'familymedicinetracker-app.firebasestorage.app',
    databaseURL: 'https://familymedicinetracker-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUte6TyQ0zzahOGdTvrXqg5NOio53TjlM',
    appId: '1:522154987711:ios:2e1fd09db6e2c9263df60a',
    messagingSenderId: '522154987711',
    projectId: 'familymedicinetracker-app',
    storageBucket: 'familymedicinetracker-app.firebasestorage.app',
    iosClientId: '522154987711-vmmdhe3nmigkrem780mk9kejmqdrrvpk.apps.googleusercontent.com',
    iosBundleId: 'org.medimitra.familyMedicineTracker',
    databaseURL: 'https://familymedicinetracker-app-default-rtdb.firebaseio.com',
  );
}
